name: Update README.md from repository

on:
  push:
    paths-ignore:
      - '.github/workflows/update-readme.yml'

jobs:
  update-readme:
    runs-on: ubuntu-22.04 # Pin to Ubuntu 22.04 LTS

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set TOKEN environment
        run: echo "TOKEN=${{ secrets.TOKENACTION }}" >> $GITHUB_ENV

      - name: Set Branch and Repository Variables
        id: set-vars
        run: |
          echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          echo "REPOSITORY=${GITHUB_REPOSITORY}" >> $GITHUB_ENV
          echo "LENGTH_LIMIT=100000" >> $GITHUB_ENV

      - name: Use UpdateREADME action from Marketplace
        uses: neutrinomuon/UpdateREADME@v0.0.4  # <--- Use the published tag
        with:
          TOKEN: ${{ env.TOKEN }}
          BRANCH: ${{ env.BRANCH }}
          REPOSITORY: ${{ env.REPOSITORY }}
          LENGTH_LIMIT: ${{ env.LENGTH_LIMIT }}
          FILE: 'README.md'
          COMMIT_MESSAGE: 'Update README with new version'
